# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACLTC Blog
email: Jmonzon0415@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Blog Site for ACLTC. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Monzon_Joshua
github_username:  Jmonzon0415

# Build settings
markdown: kramdown
